language: cpp
dist: trusty

before_install:

install:
  - sudo apt-get update 
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install -y mysql-client-core-5.6 mysql-server-5.6 mysql-client-5.6

install:
  - sudo apt-get install -qq libmysqlclient-dev
  
before_script:
  - mysql -e 'create database test_db;'

script:
  - sh main_sql.sh
  - sh custom_sql.sh
  